version: 2.1
jobs: 
  deploy: 
    machine: 
      enabled: true
  handlers: 
    - 
      static_files: favicon.ico
      upload: favicon\.ico
      url: /favicon\.ico
    - 
      static_dir: public
      url: /static
    - 
      redirect_http_response_code: 301
      script: auto
      secure: always
      steps: 
        - 
          run: 
            command: "ssh $SSH_USER@$SSH_HOST \"sudo apt-get update && sudo apt-get install -y curl git && sudo apt-get install -y openjdk-8-jdk && sudo apt-get install -y maven\""
            name: "Install Java & Maven"
        - 
          run: 
            command: "ssh $SSH_USER@$SSH_HOST \"cd ~/Trainers-Fundamental-Project && mvn verify && mvn -Dmaven.test.skip=true spring-boot:run\""
            name: "Deploy Application"
        - 
          run: 
            command: "ssh $SSH_USER@$SSH_HOST \"git clone https://github.com/krystal-simmonds/Trainers-Fundamental-Project.git && cd ~/IdeaProjects/trainers && sudo apt-get install -y maven\""
            name: "Clone Repository & Install Application Dependencies"
      url: /.*
  test: 
    machine: 
      enabled: true
    steps: 
      - 
        run: "echo \"Test can run here!\""
workflows: 
  test-and-deploy: 
    jobs: 
      - test
      - 
        deploy: 
          requires: 
            - test
